language: python

matrix:
  include:
    - os: linux
      python: "2.7"
      env: flake8=true
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.6"
    - os: osx
      language: generic
      env: PYTHON=2
    - os: osx
      language: generic
      env: PYTHON=3

# Perform the manual steps on osx to install python3 and activate venv
before_install:
    - |
       if [ "$TRAVIS_OS_NAME" = "osx" ]; then
         brew update
         if [ "$PYTHON" = "2" ]; then
           brew install python@2
           export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
         else
           brew upgrade python  # upgrade to Python 3
           export PATH="/usr/local/opt/python/libexec/bin:$PATH"
         fi
       fi

install:
  - pip install -U pytest mock six flake8 pyyaml

script:
  - python --version
  - python setup.py build_ext --inplace
  - PYTHONPATH=`pwd`/src python -m faber.platform
  - |
     if [ "$flake8" = true ]; then
       flake8 src/faber tests scripts/faber
     else
       PYTHONPATH=`pwd`/src scripts/faber --info=tools cxx
       PYTHONPATH=`pwd`/src py.test tests --compiler=native -v
     fi
